# Clock signal
set_property PACKAGE_PIN W5 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports CLK]

## 7 segment display
#set_property PACKAGE_PIN W7 [get_ports {ssd[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {ssd[0]}]
#set_property PACKAGE_PIN W6 [get_ports {ssd[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {ssd[1]}]
#set_property PACKAGE_PIN U8 [get_ports {ssd[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {ssd[2]}]
#set_property PACKAGE_PIN V8 [get_ports {ssd[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {ssd[3]}]
#set_property PACKAGE_PIN U5 [get_ports {ssd[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {ssd[4]}]
#set_property PACKAGE_PIN V5 [get_ports {ssd[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {ssd[5]}]
#set_property PACKAGE_PIN U7 [get_ports {ssd[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {ssd[6]}]

#set_property PACKAGE_PIN V7 [get_ports dp]
#set_property IOSTANDARD LVCMOS33 [get_ports dp]

set_property PACKAGE_PIN U2 [get_ports {seg_addr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_addr[0]}]
set_property PACKAGE_PIN U4 [get_ports {seg_addr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_addr[1]}]
set_property PACKAGE_PIN V4 [get_ports {seg_addr[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_addr[2]}]
set_property PACKAGE_PIN W4 [get_ports {seg_addr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_addr[3]}]

##VGA Connector
set_property PACKAGE_PIN G19 [get_ports {RGB[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[0]}]
set_property PACKAGE_PIN H19 [get_ports {RGB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[1]}]
set_property PACKAGE_PIN J19 [get_ports {RGB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[2]}]
set_property PACKAGE_PIN N19 [get_ports {RGB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[3]}]
set_property PACKAGE_PIN J17 [get_ports {RGB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[4]}]
set_property PACKAGE_PIN H17 [get_ports {RGB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[5]}]
set_property PACKAGE_PIN G17 [get_ports {RGB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[6]}]
set_property PACKAGE_PIN D17 [get_ports {RGB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[7]}]
set_property PACKAGE_PIN N18 [get_ports {RGB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[8]}]
set_property PACKAGE_PIN L18 [get_ports {RGB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[9]}]
set_property PACKAGE_PIN K18 [get_ports {RGB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[10]}]
set_property PACKAGE_PIN J18 [get_ports {RGB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[11]}]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]

##Buttons
set_property PACKAGE_PIN U18 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property PACKAGE_PIN T18 [get_ports btnU]
set_property IOSTANDARD LVCMOS33 [get_ports btnU]
set_property PACKAGE_PIN W19 [get_ports btnL]
set_property IOSTANDARD LVCMOS33 [get_ports btnL]
set_property PACKAGE_PIN T17 [get_ports btnR]
set_property IOSTANDARD LVCMOS33 [get_ports btnR]
set_property PACKAGE_PIN U17 [get_ports btnD]
set_property IOSTANDARD LVCMOS33 [get_ports btnD]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
